minimumReleaseAge: 2880

overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@0.3.3
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - vitest
  - '@vitest/*'
